### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by ssaru** [sunshineatnoon/Darknet.keras#10]
return empty list from np.fromfile at TinyYoloNet.py, ReadTinyYOLONetWeights. line 76

how to fix it?

![screenshot from 2017-06-22 22-06-18](https://user-images.githubusercontent.com/13328380/27435390-0eb2b85e-5797-11e7-8fd7-800112a3c11e.png)

**Comment by sunshineatnoon** [comment]
Maybe https://github.com/sunshineatnoon/Darknet.keras/issues/5 can help you. This repo based on the old YOLO weight, now YOLO has updated to 2.0. So you might need the old weight [here](http://pjreddie.com/media/files/yolo-tiny.weights).

**Comment by ssaru** [comment]
it's look like read weights file!

but... i getting another error!

Traceback (most recent call last):
  File "RunTinyYOLO.py", line 209, in <module>
    model = SimpleNet(yoloNet)
  File "RunTinyYOLO.py", line 38, in SimpleNet
    model.add(Convolution2D(16, 3, 3, weights=[yoloNet.layers[1].weights,yoloNet.layers[1].biases],border_mode='valid',subsample=(1,1)))
  File "/home/martin/Documents/enumnet/goverment_project/Deeplearning/Study/keras-darknet/env/lib/python3.5/site-packages/keras/models.py", line 476, in add
    output_tensor = layer(self.outputs[0])
  File "/home/martin/Documents/enumnet/goverment_project/Deeplearning/Study/keras-darknet/env/lib/python3.5/site-packages/keras/engine/topology.py", line 576, in __call__
    self.set_weights(self._initial_weights)
  File "/home/martin/Documents/enumnet/goverment_project/Deeplearning/Study/keras-darknet/env/lib/python3.5/site-packages/keras/engine/topology.py", line 1190, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (3, 3, 448, 16) not compatible with provided weight shape (16, 3, 3, 3)


![screenshot from 2017-06-23 11-09-01](https://user-images.githubusercontent.com/13328380/27463759-a2ed2474-5804-11e7-9416-409cb8e5e785.png)

**Comment by Abduoit** [comment]
Hi, I tried with the old weight but still getting error 

abdulrahman@abdulrahman-ThinkPad-X230-Tablet:~/Darknet.keras$ python RunTinyYOLO.py
Traceback (most recent call last):
  File "RunTinyYOLO.py", line 6, in <module>
    from utils.crop import crop
  File "/home/abdulrahman/Darknet.keras/utils/crop.py", line 3, in <module>
    from scipy import misc
ImportError: No module named scipy

**Comment by ssaru** [comment]
@Abduoit 
I think that you should install scipy module

pip install scipy
Or 
pip3 install scipy

**Comment by Abduoit** [comment]
Thx @SsaRu 
I did
Now I get the following error

abdulrahman@abdulrahman-ThinkPad-X230-Tablet:~/Darknet.keras$ python RunTinyYOLO.py
Traceback (most recent call last):
  File "RunTinyYOLO.py", line 8, in <module>
    from keras.models import Sequential
ImportError: No module named keras.models

**Comment by ssaru** [comment]
You installed keras? With tensorflow
1. You should install tensorflow
And after 
pip install keras

**Comment by Abduoit** [comment]
@SsaRu 
I do have tensorflow and keras and theano
now I am getting the following error 

abdulrahman@abdulrahman-ThinkPad-X230-Tablet:~/Darknet.keras$ python RunTinyYOLO.py
Using TensorFlow backend.
RunTinyYOLO.py:38: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(16, (3, 3), padding="valid", strides=(1, 1), weights=[array([[[...)`
  model.add(Convolution2D(16, 3, 3, weights=[yoloNet.layers[1].weights,yoloNet.layers[1].biases],border_mode='valid',subsample=(1,1)))
Traceback (most recent call last):
  File "RunTinyYOLO.py", line 209, in <module>
    model = SimpleNet(yoloNet)
  File "RunTinyYOLO.py", line 38, in SimpleNet
    model.add(Convolution2D(16, 3, 3, weights=[yoloNet.layers[1].weights,yoloNet.layers[1].biases],border_mode='valid',subsample=(1,1)))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 469, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 576, in __call__
    self.set_weights(self._initial_weights)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 1190, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (3, 3, 448, 16) not compatible with provided weight shape (16, 3, 3, 3)

**Comment by ssaru** [comment]
Yes good! 
Now you got error messagr that same with me
Im waiting author's answer :)

**Comment by sunshineatnoon** [comment]
@SsaRu I don't have access to a machine with GPU, so probably will not fix this bug. You might want to try other YOLO implementations: [Tensorflow Version](https://github.com/nilboy/tensorflow-yolo) or [Pytorch Version(YOLO2)](https://github.com/longcw/yolo2-pytorch)

**Comment by ssaru** [comment]
Ok! i will try!
thanks :) !!
